export const StatActionTypes = {
  SET_CURRENT_COUNTRY: 'SET_CURRENT_COUNTRY',
  GET_STATS_BY_COUNTRY: 'GET_STATS_BY_COUNTRY',
  GET_STATS_BY_COUNTRY_SUCCESS: 'GET_STATS_BY_COUNTRY_SUCCESS',
  GET_STATS_BY_COUNTRY_FAILED: 'GET_STATS_BY_COUNTRY_FAILED',
  GET_ALL_STATS: 'GET_ALL_STATS',
  GET_ALL_STATS_SUCCESS: 'GET_ALL_STATS_SUCCESS',
  GET_ALL_STATS_FAILED: 'GET_ALL_STATS_FAILED',
  RESET_ALERT_NO_DATA_AVAILABLE: 'RESET_ALERT_NO_DATA_AVAILABLE',
};
